# -*- coding: utf-8 -*-
"""Задание_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iqd8-wVws7fKBZ1QjiI8WyefjQKfAKGX
"""

#Задание 2
# https://www.codewars.com/kata/reviews/545d21e99943f78e6d0000df/groups/545d29831288c1e3670009c8
def string_to_number(s):
    return int(s)

# Выполнено
