# -*- coding: utf-8 -*-
"""Задание_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rGQ2Z5NkojYpERpnGwbxtDZvS91QMPEc
"""

#Задание 1
# https://www.codewars.com/kata/reviews/580cfb2092a920b4b2000013/groups/580d050d4c7886c7680005ae
def switch_it_up(number):
    return {0: 'Zero', 1: 'One', 2: 'Two', 3: 'Three', 4: 'Four', 5: 'Five',
            6: 'Six', 7: 'Seven', 8: 'Eight', 9: 'Nine'}.get(number)

# Выполнено
